apiVersion: v1
kind: Service
metadata:
  name: post-srv-node-port
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 3002
      targetPort: 3002